name: Static Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or another LTS/Boron version

      # Install your project dependencies
      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      # - name: Lint
      #   run: |
      #     pnpm run lint

      # # Conduct TypeScript type checks
      # - name: Type checks
      #   working-directory: ./app
      #   run: |
      #     pnpm run type:check

      # Conduct style checks using Prettier
      - name: Prettier style check
        run: |
          pnpm run format:check
